// Build Script: Generate Environment Configuration
// This script creates the env-config.js file for the built site
// It reads from environment variables at build time

const fs = require('fs');
const path = require('path');

function generateEnvConfig() {
  // Read environment variables
  const config = {
    SUPABASE_URL: process.env.SUPABASE_URL || '',
    SUPABASE_KEY: process.env.SUPABASE_KEY || '',
    UPI_ID: process.env.UPI_ID || '',
    UPI_MERCHANT_NAME: process.env.UPI_MERCHANT_NAME || 'Mindful Living & Devotional Music',
    SITE_URL: process.env.SITE_URL || 'https://ecoliving-tips.github.io'
  };

  // Generate JavaScript config
  const jsContent = `// Environment Configuration
// DO NOT EDIT THIS FILE MANUALLY
// This file is auto-generated at build time from environment variables

window.ENV = ${JSON.stringify(config, null, 2)};
`;

  // Write to _includes for Eleventy to include
  const outputPath = path.join(__dirname, '..', '_includes', 'env-config.njk');
  
  // Create Nunjucks output
  const njkContent = `<!-- Environment Configuration -->
<script>
window.ENV = ${JSON.stringify(config, null, 2)};
</script>
`;

  fs.writeFileSync(outputPath, njkContent);
  console.log('✅ Environment config generated');
}

generateEnvConfig();
